# Generated by Django 5.1.4 on 2025-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_contact_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='buynow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
