# Generated by Django 5.1.4 on 2025-02-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_buynow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buynow',
            new_name='product',
        ),
    ]
